# Generated by Django 2.0.3 on 2018-03-07 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sect', models.CharField(max_length=2)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.speakers')),
            ],
        ),
    ]
