# Generated by Django 2.0.3 on 2018-03-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180307_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.speakers'),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
