# Generated by Django 2.0.3 on 2018-03-07 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180307_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sect',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='sect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
    ]
