# Generated by Django 2.0.3 on 2018-03-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180307_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='sect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
    ]
