# Generated by Django 2.0.3 on 2018-03-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180312_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='sect',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
    ]
