# Generated by Django 2.0.3 on 2018-03-12 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20180312_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='sect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
    ]
